### ISSUE TITLE
Is it possible to convert file encoding?

### ISSUE THREAD

**Issue by sukeyisme** [abo-abo/make-it-so#6]

**Comment by abo-abo** [comment]
Please clarify. I have no idea what you want.

**Comment by sukeyisme** [comment]
for example : convert a file from gb2312 to utf8

**Comment by abo-abo** [comment]
Try this one. It converts txt files to utf8.

**Comment by sukeyisme** [comment]
dir: command not found on osx

**Comment by abo-abo** [comment]
`dir` is part of GNU coreutils. You need to install `coreutils` for OSX.

**Comment by sukeyisme** [comment]
Thanks, but i don't know why use dir,could be ls? if not could be "alias dir = ls -C -b"? i don't want to    install coreutils just because one command.

**Comment by abo-abo** [comment]
> alias dir = ls -C -b

This should work, just put that in `~/.bashrc`.

**Comment by sukeyisme** [comment]
i still install coreutils :) , i could not find ~/.bashrc on my mac .

**Comment by sukeyisme** [comment]
I found /bin/sh on mac is not linking to bash,and only read ~/.profile when start with --login. So when i set zsh as my default shell,i should use your package start /bin/sh with --login,and put alias dir="ls -C -b" in ~/.profile.Now it work.

**Comment by abo-abo** [comment]
Weird, maybe another person using OSX can comment? I'm sure someone was bound to encounter and solve the above problem.

**Comment by sukeyisme** [comment]
:) After convert the file name and the original file name is not the same, but also need to modify their own.

**Comment by abo-abo** [comment]
> After convert the file name and the original file name is not the same, but also need to modify their own

You should modify the Makefile if you don't like how it works. It can be made to replace the original file.
