### ISSUE TITLE
Can't run gifsicle after failure

### ISSUE THREAD

**Issue by DamienCassou** [abo-abo/make-it-so#9]
How to reproduce:

1. uninstall gifsicle
2. `M-x make-it-so` on a list of gif files
3. select gifsicle
4. `M-x mis-save-and-compile`
5. you get a message saying you miss gifsicle
6. install gifsicle
7. `M-x mis-save-and-compile`
8. You get a message saying there is nothing to do

I expect to get an animated gif instead at step 8.

Workaround, between steps 6 and 7, remove the empty `animate.gif`.

**Comment by abo-abo** [comment]
Thanks.
